[package]
name = "eid-reader"
version = "1.0.0"
edition = "2021"
authors = ["Sophia"]
description = "Belgian eID Reader Application"

[package.metadata.windows]
subsystem = "windows"

[dependencies]
rocket = "0.5"
base64 = "0.21"
clap = { version = "4.0", features = ["derive"] }
cryptoki = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
os_type = "2.6"
windows-service = "0.5"