[package]
name = "rust-eidreader"
version = "0.1.7"
edition = "2021"

[dependencies]
base64 = "0.21.0"
cryptoki = { version = "0.9.0",  git = "https://github.com/parallaxsecond/rust-cryptoki"}
cryptoki-sys = "0.1.6"
os_type = "2.6.0"
serde = "1.0.158"
serde_json = "1.0.94"
clap = { version = "4.5.3", features = ["derive"] }

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json", "tls"]

[[bin]]
name = "EIDReader"
path = "src/main.rs"